name = "unihack-2026"
main = ".output/server/index.mjs"
compatibility_date = "2024-03-13"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"
binding = "ASSETS"

[observability]
enabled = true
