/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthedReplayRouteImport } from './routes/_authed/replay'
import { Route as AuthedRecordRouteImport } from './routes/_authed/record'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedLeaderboardRouteImport } from './routes/_authed/leaderboard'
import { Route as AuthedDriverMonitorRouteImport } from './routes/_authed/driver-monitor'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedReplayRoute = AuthedReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecordRoute = AuthedRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeaderboardRoute = AuthedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDriverMonitorRoute = AuthedDriverMonitorRouteImport.update({
  id: '/driver-monitor',
  path: '/driver-monitor',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/driver-monitor': typeof AuthedDriverMonitorRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/profile': typeof AuthedProfileRoute
  '/record': typeof AuthedRecordRoute
  '/replay': typeof AuthedReplayRoute
  '/api/$': typeof ApiSplatRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/driver-monitor': typeof AuthedDriverMonitorRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/profile': typeof AuthedProfileRoute
  '/record': typeof AuthedRecordRoute
  '/replay': typeof AuthedReplayRoute
  '/api/$': typeof ApiSplatRoute
  '/api/tts': typeof ApiTtsRoute
  '/': typeof AuthedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_authed/driver-monitor': typeof AuthedDriverMonitorRoute
  '/_authed/leaderboard': typeof AuthedLeaderboardRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/record': typeof AuthedRecordRoute
  '/_authed/replay': typeof AuthedReplayRoute
  '/api/$': typeof ApiSplatRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/driver-monitor'
    | '/leaderboard'
    | '/onboarding'
    | '/profile'
    | '/record'
    | '/replay'
    | '/api/$'
    | '/api/tts'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/driver-monitor'
    | '/leaderboard'
    | '/onboarding'
    | '/profile'
    | '/record'
    | '/replay'
    | '/api/$'
    | '/api/tts'
    | '/'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/_authed'
    | '/about'
    | '/login'
    | '/_authed/driver-monitor'
    | '/_authed/leaderboard'
    | '/_authed/onboarding'
    | '/_authed/profile'
    | '/_authed/record'
    | '/_authed/replay'
    | '/api/$'
    | '/api/tts'
    | '/_authed/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/replay': {
      id: '/_authed/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof AuthedReplayRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/record': {
      id: '/_authed/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof AuthedRecordRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leaderboard': {
      id: '/_authed/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthedLeaderboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/driver-monitor': {
      id: '/_authed/driver-monitor'
      path: '/driver-monitor'
      fullPath: '/driver-monitor'
      preLoaderRoute: typeof AuthedDriverMonitorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDriverMonitorRoute: typeof AuthedDriverMonitorRoute
  AuthedLeaderboardRoute: typeof AuthedLeaderboardRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedRecordRoute: typeof AuthedRecordRoute
  AuthedReplayRoute: typeof AuthedReplayRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDriverMonitorRoute: AuthedDriverMonitorRoute,
  AuthedLeaderboardRoute: AuthedLeaderboardRoute,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedRecordRoute: AuthedRecordRoute,
  AuthedReplayRoute: AuthedReplayRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
